import uk.gov.hmrc.versioning.SbtGitVersioning.autoImport.majorVersion
import uk.gov.hmrc.DefaultBuildSettings

val appName = "eeitt-admin-frontend"

lazy val microservice = Project(appName, file("."))
  .enablePlugins(
    play.sbt.PlayScala,
    SbtAutoBuildPlugin,
    SbtGitVersioning,
    SbtDistributablesPlugin
  )
  .settings(DefaultBuildSettings.scalaSettings: _*)
  .settings(DefaultBuildSettings.defaultSettings(): _*)
  .settings(
    organization := "uk.gov.hmrc",
    majorVersion := 1,
    scalaVersion := "2.12.15",
    scalafmtOnCompile := true,
    PlayKeys.playDefaultPort := 9199,
    libraryDependencies ++= AppDependencies.compile ++ AppDependencies.test()
  )
  .settings(
    scalacOptions ++= Seq(
      "-Xfatal-warnings",
      "-Xlint:-missing-interpolator,_",
      "-Yno-adapted-args",
      "-Ywarn-numeric-widen",
      "-Ywarn-value-discard",
      "-Ywarn-dead-code",
      "-deprecation",
      "-feature",
      "-unchecked",
      // silence all warnings on autogenerated files and
      // twirl templates. (Not all twirl templates use all TwirlKeys.templateImports)
      "-Wconf:src=twirl/.*:silent,src=routes/.*:silent"
    )
  )
  .settings(
    resolvers ++= Seq(
      Resolver.bintrayRepo("jetbrains", "markdown"),
      Resolver.jcenterRepo,
      "bintray-djspiewak-maven" at "https://dl.bintray.com/djspiewak/maven",
      "bintray" at "https://dl.bintray.com/webjars/maven"
    )
  )
  .settings(
    TwirlKeys.templateImports ++= Seq(
      "play.twirl.api.Html",
      "play.twirl.api.HtmlFormat",
      "uk.gov.hmrc.eeittadminfrontend.models._"
    ),
    routesImport ++= Seq(
      "uk.gov.hmrc.eeittadminfrontend.binders.ValueClassBinders._",
      "uk.gov.hmrc.eeittadminfrontend.models.FormTemplateId",
      "uk.gov.hmrc.eeittadminfrontend.models.FormId",
      "uk.gov.hmrc.eeittadminfrontend.models.fileupload.EnvelopeId",
      "uk.gov.hmrc.eeittadminfrontend.deployment._",
      "uk.gov.hmrc.eeittadminfrontend.models.sdes.CorrelationId",
      "uk.gov.hmrc.eeittadminfrontend.models.sdes.SubmissionRef"
    )
  )
