import uk.gov.hmrc.versioning.SbtGitVersioning.autoImport.majorVersion
import uk.gov.hmrc.DefaultBuildSettings

val appName = "eeitt-admin-frontend"
ThisBuild / majorVersion := 1
ThisBuild / scalaVersion := "2.13.16"

lazy val microservice = Project(appName, file("."))
  .enablePlugins(
    play.sbt.PlayScala,
    SbtDistributablesPlugin
  )
  .settings(
    organization := "uk.gov.hmrc",
    scalafmtOnCompile := true,
    PlayKeys.playDefaultPort := 9199,
    libraryDependencies ++= AppDependencies.compile ++ AppDependencies.test()
  )
  .settings(
    scalacOptions ++= Seq(
      "-Xfatal-warnings",
      "-Xlint:-missing-interpolator,_",
      "-Xlint:-byname-implicit",
      "-Ywarn-numeric-widen",
      "-Ywarn-value-discard",
      "-Ywarn-dead-code",
      "-deprecation",
      "-feature",
      "-unchecked",
      // silence all warnings on autogenerated files and
      // twirl templates. (Not all twirl templates use all TwirlKeys.templateImports)
      "-Wconf:src=twirl/.*:silent,src=routes/.*:silent"
    )
  )
  .settings(
    TwirlKeys.templateImports ++= Seq(
      "play.twirl.api.Html",
      "play.twirl.api.HtmlFormat",
      "uk.gov.hmrc.eeittadminfrontend.models._",
      "uk.gov.hmrc.govukfrontend.views.html.components.implicits._",
      "uk.gov.hmrc.govukfrontend.views.html.components._"
    ),
    routesImport ++= Seq(
      "uk.gov.hmrc.eeittadminfrontend.binders.ValueClassBinders._",
      "uk.gov.hmrc.eeittadminfrontend.history.HistoryId",
      "uk.gov.hmrc.eeittadminfrontend.models.FormTemplateRawId",
      "uk.gov.hmrc.eeittadminfrontend.models.FormTemplateId",
      "uk.gov.hmrc.eeittadminfrontend.models.FormId",
      "uk.gov.hmrc.eeittadminfrontend.models.fileupload.EnvelopeId",
      "uk.gov.hmrc.eeittadminfrontend.deployment._",
      "uk.gov.hmrc.eeittadminfrontend.models.sdes._",
      "uk.gov.hmrc.eeittadminfrontend.models.BannerId",
      "uk.gov.hmrc.eeittadminfrontend.models.ShutterMessageId",
      "uk.gov.hmrc.play.bootstrap.binders.RedirectUrl",
      "uk.gov.hmrc.eeittadminfrontend.translation.TranslationAuditId"
    )
  )
